apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptopix
  labels:
    app: cryptopix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cryptopix
  template:
    metadata:
      labels:
        app: cryptopix
    spec:
      containers:
      - name: cryptopix
        image: ghcr.io/etherian3/cryptopix:sha-8bc252e07ac076a911b5bd30463101e1ee35607c
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: github-container-registry